### ISSUE TITLE
Error on line 79:33

### ISSUE THREAD

**Issue by twcau** [dwd0tcom/strava-scriptable-widget#1]
Whenever running this script per documentation, it persistently returns the following error:

Exception Occured 
Error on line 79:33: TypeError: undefined is not an object (evaluating ‘data[0].name’)

Also, could you reconsider the method of configuration. Passing the API information as a parameter, rather than just allowing the user to store it as a const in the script is rather inefficient and is a real barrier to use (your current method of Constructing the information as a shortcut is unnecessarily complex).

**Comment by twcau** [comment]
This issue also persists in the commit as of 19min ago.

**Comment by dwd0tcom** [comment]
The method of passing the information as parameter is pretty normal to scriptable users. 

It seems like something is wrong with your parameters. Did you use the shortcut to create these?
