### ISSUE TITLE
Issue with the data.photo

### ISSUE THREAD

**Issue by samanthsatya** [dwd0tcom/strava-scriptable-widget#2]
I am seeing the below error after adding the widget and following the steps![image](https://user-images.githubusercontent.com/72437849/138390658-6d00552e-1f8d-4084-93d2-a588b91854bc.jpeg)

**Comment by schlikkes** [comment]
I have the same issue.

**Comment by dwd0tcom** [comment]
It seems like, it has an issue with pulling the photo. Just to clarify, are you a paid member?

**Comment by AlexSpaeth1976** [comment]
Same problem! I‘m a paid meiner.

**Comment by dwd0tcom** [comment]
Okay, so it has nothing to do with this. That's cool. Did you complete the steps to create your own Strava app and did you run the shortcuts widget?

**Comment by AlexSpaeth1976** [comment]
> Okay, so it has nothing to do with this. That's cool. Did you complete the steps to create your own Strava app and did you run the shortcuts widget?

Yes, i complete the App creation process, but the short cut did not work, so i put the three needed values manually in the Script parameter field!

**Comment by dwd0tcom** [comment]
I guess some iOS update messed up the script for shortcuts. I'll check this!

**Comment by AlexSpaeth1976** [comment]
> I guess some iOS update messed up the script for shortcuts. I'll check this!

Sounds good!

**Comment by dwd0tcom** [comment]
So it seems like, strava changed something with it's API since I can't pull data from the URL with GET. Working on it right now!

**Comment by dwd0tcom** [comment]
Okay, nevermind. Everything works, I just forgot to add the action to add everything to your clipboard.

**Comment by dwd0tcom** [comment]
This might also fix #3 
I edited the shortcut and it now should output your credentials for the widget. Can you please check this: https://www.icloud.com/shortcuts/57a5bb786c61414ea6fb4fb062421bcf

**Comment by AlexSpaeth1976** [comment]
> This might also fix #3
> I edited the shortcut and it now should output your credentials for the widget. Can you please check this: https://www.icloud.com/shortcuts/57a5bb786c61414ea6fb4fb062421bcf

Don’t work!

Only 2 Parameters in the clipboard!

**Comment by AlexSpaeth1976** [comment]
I agree everything!
But i don’t work in a correct way!
Here is the sequence:

![56420F9E-505E-4E65-B680-38DFAF4497F0](https://user-images.githubusercontent.com/93878380/140735918-56c4c6ad-d107-4d58-a77e-27ac2c4dd82a.png)
![B5CC41B1-C07F-4926-9A1E-C1BB7C8B933A](https://user-images.githubusercontent.com/93878380/140735882-b2e83478-4886-454e-a2fe-3c3785f778cc.png)
![B9FB3EEF-3390-4E12-AF84-2EAE65C4C964](https://user-images.githubusercontent.com/93878380/140735891-cbede860-630e-4ea4-9268-025b26795e5d.png)
![2F9B17EC-281B-41B3-8F89-12A6AA1BEB20](https://user-images.githubusercontent.com/93878380/140735897-c2a15296-fd1f-4931-8cee-b38f03497847.png)
![E5A91245-F2A1-49AE-86FD-300B26B688C6](https://user-images.githubusercontent.com/93878380/140735906-92cf076a-f8b5-4cc9-8b86-7cd868a72dfc.png)
![4D8FE069-BB58-4D3B-88B0-2F28B9C917DD](https://user-images.githubusercontent.com/93878380/140735909-43228f76-01e6-4506-8c5e-a9421e82545e.jpeg)
![5F3699D8-791E-4A93-9732-81390489AA1D](https://user-images.githubusercontent.com/93878380/140735914-088fba6e-aed9-4a42-9b44-305d5f1687f6.jpeg)

**Comment by dwd0tcom** [comment]
It seems like you're missing out one step. 

1. Enter your ClientID (That's the short one)
2. Enter your ClientSecret
3. Wait until you get the prompt to login to your Strava Account
4. Authorize your app
5. Safari tells you about an error, press share and copy **before** pressing done (a link should be in your clipboard)
6. Shortcuts checks now for this link, to be sure everything works press "immer erlauben"
7. Your credentials should be created by now

**Comment by AlexSpaeth1976** [comment]
> It seems like you're missing out one step.
> 
> 1. Enter your ClientID (That's the short one)
> 2. Enter your ClientSecret
> 3. Wait until you get the prompt to login to your Strava Account
> 4. Authorize your app
> 5. Safari tells you about an error, press share and copy **before** pressing done (a link should be in your clipboard)
> 6. Shortcuts checks now for this link, to be sure everything works press "immer erlauben"
> 7. Your credentials should be created by now

Shortcut works now, but still the error message with data.photo….

**Comment by AlexSpaeth1976** [comment]
> > It seems like you're missing out one step.
> > 
> > 1. Enter your ClientID (That's the short one)
> > 2. Enter your ClientSecret
> > 3. Wait until you get the prompt to login to your Strava Account
> > 4. Authorize your app
> > 5. Safari tells you about an error, press share and copy **before** pressing done (a link should be in your clipboard)
> > 6. Shortcuts checks now for this link, to be sure everything works press "immer erlauben"
> > 7. Your credentials should be created by now
> 
> Shortcut works now, but still the error message with data.photo….

![D358EEFC-2029-4471-8B7C-855E84181328](https://user-images.githubusercontent.com/93878380/140811174-36a66823-b76d-408e-a710-f28f42b6a9f4.jpeg)

**Comment by dwd0tcom** [comment]
You're still using the wrong credentials. Because it's giving you null. That means, there is no data to get a photo. Are you sure the shortcut is running? 😅

**Comment by dwd0tcom** [comment]
Oh. Forget everything. Strava is having Server issues: https://status.strava.com/

**Comment by AlexSpaeth1976** [comment]
> Oh. Forget everything. Strava is having Server issues: https://status.strava.com/
> 
> It should work just fine, when the server is back 

> Oh. Forget everything. Strava is having Server issues: https://status.strava.com/
> 
> It should work just fine, when the server is back up!

Ok… Hm… sounds a little bit strange!
Sure that your script is working?

If i type in the parameters in the widget, it makes the same strange things!
![2B2695D2-0BA2-47C8-A7B2-8CBC17DBCAC9](https://user-images.githubusercontent.com/93878380/140813996-ec3a39e9-516d-439a-ab24-03a92d81e02d.jpeg)

**Comment by dwd0tcom** [comment]
Yes, sure it's working. 😃 
When there is no server, where should it get data from? Check back now, it's fixed and the server is back up.

**Comment by AlexSpaeth1976** [comment]
> Yes, sure it's working. 😃
> When there is no server, where should it get data from? Check back now, it's fixed and the server is back up.

Now it works! Thanks for your support! 😉👍🏻

**Comment by dwd0tcom** [comment]
Perfect! Glad we figured it out!

**Comment by MAT-GRC** [comment]
hello, i have the same problem but your issue doesn't work for me.

**Comment by iruahn** [comment]
Hi, I have same issue as above. 

Is it support to only paid member?

> data.photo….

**Comment by dwd0tcom** [comment]
Did you try all the steps which I mentioned earlier in this Issue?
No, it's also for free members.

**Comment by iruahn** [comment]
When I was debugging for shortcut, got some strange. 
It is the return of URL below. 
Return : {"message":"Bad Request","errors":[{"field":"code","code":"invalid","resource":"AuthorizationCode"}]}
URL : https://www.strava.com/oauth/token?client_id=clientId&client_secret=clientSecret&code=authCode&grant_type=authorization_code

**Comment by dwd0tcom** [comment]
Ok, it's pretty hard for me to get this figured out. Where did you get the error? Did you input your credentials correctly? One error is intended. See the instructions for this. Otherwise I would ask you to open a new Issue, since this is already closed.
