### ISSUE TITLE
Error on line 135:24:TypeError: null is not an object (evaluating 'data.total_photo_count')

### ISSUE THREAD

**Issue by flow23** [dwd0tcom/strava-scriptable-widget#4]
Hi,

I get this error. I set photoWidget preview to false. True does also not work.

**Comment by dwd0tcom** [comment]
Hey @flow23, thanks for your report. 
This happens, when the API endpoint is not available. If it's not available, there is no object for the photo and it simply can't get "data.total_photo_count". Does it work now?

**Comment by flow23** [comment]
No, still happening.

**Comment by dwd0tcom** [comment]
Did you set up everything correct? Did it ever work? This was a known bug before I released an updated version of the shortcut. So I guess it's not the script.

**Comment by dwd0tcom** [comment]
Just tested everything and if you're using the latest Shortcut and if you're doing **every** step of the procedure, it'll work.
