### ISSUE TITLE
page not found in second step

### ISSUE THREAD

**Issue by abjeroen** [dwd0tcom/strava-scriptable-widget#5]
I do get the authorize page where I can confirm to use the app. However, in the second step I keep getting an error that the page does not exist. It's this url that causes the trouble: https://www.strava.com/oauth/token?client_id=123&client_secret=123&code=123&grant_type=authorization_code . Can you confirm that it is still working on your side?

**Comment by dwd0tcom** [comment]
This is intended. See the install instructions.
