### ISSUE TITLE
Images do not load

### ISSUE THREAD

**Issue by dwd0tcom** [dwd0tcom/strava-scriptable-widget#7]
Something changed on Strava's API. I can't find anything in their changelog, so I need to wait until I can fix this

**Comment by dwd0tcom** [comment]
Ok, seems to be a problem. Found this on Google Groups (wtf? 😃) https://groups.google.com/g/strava-api/c/vVqL__iZ2bU

**Comment by psycho0verload** [comment]
With this he gives me an error. In the API documentation total_photo_count is still described though

**Comment by dwd0tcom** [comment]
Yes, kinda weird! Even in Swagger the response for total_photo_count is always 0

**Comment by dwd0tcom** [comment]
Strava fixed it.
